# Generated by Django 5.0 on 2025-12-29 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        db_index=True, max_length=20, unique=True, verbose_name="Número"
                    ),
                ),
                ("nome", models.CharField(max_length=120, verbose_name="Nome")),
                (
                    "nome_formal",
                    models.CharField(max_length=255, verbose_name="Nome Formal"),
                ),
                (
                    "nif",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="NIF"
                    ),
                ),
                (
                    "morada",
                    models.TextField(blank=True, null=True, verbose_name="Morada"),
                ),
                (
                    "pais",
                    models.CharField(
                        blank=True,
                        default="Portugal",
                        max_length=100,
                        null=True,
                        verbose_name="País",
                    ),
                ),
                (
                    "contacto",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Contacto"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=255, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "angariacao",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Angariação"
                    ),
                ),
                ("nota", models.TextField(blank=True, null=True, verbose_name="Nota")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "db_table": "clientes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Fornecedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        db_index=True, max_length=20, unique=True, verbose_name="Número"
                    ),
                ),
                ("nome", models.CharField(max_length=255, verbose_name="Nome")),
                (
                    "estatuto",
                    models.CharField(
                        choices=[
                            ("EMPRESA", "Empresa"),
                            ("FREELANCER", "Freelancer"),
                            ("ESTADO", "Estado"),
                        ],
                        default="FREELANCER",
                        max_length=20,
                        verbose_name="Estatuto",
                    ),
                ),
                (
                    "area",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Área"
                    ),
                ),
                (
                    "funcao",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Função"
                    ),
                ),
                (
                    "classificacao",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Classificação"
                    ),
                ),
                (
                    "validade_seguro_trabalho",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Validade Seguro Trabalho"
                    ),
                ),
                (
                    "nif",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="NIF"
                    ),
                ),
                (
                    "iban",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="IBAN"
                    ),
                ),
                (
                    "morada",
                    models.TextField(blank=True, null=True, verbose_name="Morada"),
                ),
                (
                    "pais",
                    models.CharField(
                        blank=True,
                        default="Portugal",
                        max_length=100,
                        null=True,
                        verbose_name="País",
                    ),
                ),
                (
                    "contacto",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Contacto"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=255, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True, max_length=255, null=True, verbose_name="Website"
                    ),
                ),
                ("nota", models.TextField(blank=True, null=True, verbose_name="Nota")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Fornecedor",
                "verbose_name_plural": "Fornecedores",
                "db_table": "fornecedores",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        db_index=True, max_length=20, unique=True, verbose_name="Número"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("EMPRESA", "Empresa"), ("PESSOAL", "Pessoal")],
                        db_index=True,
                        default="EMPRESA",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "owner",
                    models.CharField(default="BA", max_length=2, verbose_name="Owner"),
                ),
                (
                    "data_inicio",
                    models.DateField(blank=True, null=True, verbose_name="Data Início"),
                ),
                (
                    "data_fim",
                    models.DateField(blank=True, null=True, verbose_name="Data Fim"),
                ),
                ("descricao", models.TextField(verbose_name="Descrição")),
                (
                    "valor_sem_iva",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Valor sem IVA",
                    ),
                ),
                (
                    "data_faturacao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Faturação"
                    ),
                ),
                (
                    "data_vencimento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Vencimento"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("ATIVO", "Ativo"),
                            ("FINALIZADO", "Finalizado"),
                            ("PAGO", "Pago"),
                            ("ANULADO", "Anulado"),
                        ],
                        db_index=True,
                        default="ATIVO",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "premio_bruno",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                        verbose_name="Prémio Bruno",
                    ),
                ),
                (
                    "premio_rafael",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                        verbose_name="Prémio Rafael",
                    ),
                ),
                ("nota", models.TextField(blank=True, null=True, verbose_name="Nota")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projetos",
                        to="core.cliente",
                        verbose_name="Cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Projeto",
                "verbose_name_plural": "Projetos",
                "db_table": "projetos",
                "ordering": ["-created_at"],
            },
        ),
    ]
