# Generated by Django 5.0 on 2025-12-29 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DespesaTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        db_index=True, max_length=20, unique=True, verbose_name="Número"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("FIXA_MENSAL", "Fixa Mensal"),
                            ("PESSOAL_BA", "Pessoal BA"),
                            ("PESSOAL_RR", "Pessoal RR"),
                            ("EQUIPAMENTO", "Equipamento"),
                            ("PROJETO", "Projeto"),
                        ],
                        db_index=True,
                        default="FIXA_MENSAL",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                ("descricao", models.TextField(verbose_name="Descrição")),
                (
                    "valor_sem_iva",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Valor sem IVA",
                    ),
                ),
                (
                    "valor_com_iva",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Valor com IVA",
                    ),
                ),
                ("dia_mes", models.IntegerField(verbose_name="Dia do Mês")),
                ("nota", models.TextField(blank=True, null=True, verbose_name="Nota")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "credor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.fornecedor",
                        verbose_name="Credor",
                    ),
                ),
                (
                    "projeto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.projeto",
                        verbose_name="Projeto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Template de Despesa",
                "verbose_name_plural": "Templates de Despesa",
                "db_table": "despesa_templates",
                "ordering": ["dia_mes", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Despesa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        db_index=True, max_length=20, unique=True, verbose_name="Número"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("FIXA_MENSAL", "Fixa Mensal"),
                            ("PESSOAL_BA", "Pessoal BA"),
                            ("PESSOAL_RR", "Pessoal RR"),
                            ("EQUIPAMENTO", "Equipamento"),
                            ("PROJETO", "Projeto"),
                        ],
                        db_index=True,
                        default="FIXA_MENSAL",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                ("data", models.DateField(db_index=True, verbose_name="Data")),
                ("descricao", models.TextField(verbose_name="Descrição")),
                (
                    "valor_sem_iva",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Valor sem IVA",
                    ),
                ),
                (
                    "valor_com_iva",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Valor com IVA",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("VENCIDO", "Vencido"),
                            ("PAGO", "Pago"),
                        ],
                        db_index=True,
                        default="PENDENTE",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "data_pagamento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Pagamento"
                    ),
                ),
                ("nota", models.TextField(blank=True, null=True, verbose_name="Nota")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "credor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="despesas",
                        to="core.fornecedor",
                        verbose_name="Credor",
                    ),
                ),
                (
                    "projeto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="despesas",
                        to="core.projeto",
                        verbose_name="Projeto",
                    ),
                ),
                (
                    "despesa_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="despesas_geradas",
                        to="core.despesatemplate",
                        verbose_name="Template de Origem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Despesa",
                "verbose_name_plural": "Despesas",
                "db_table": "despesas",
                "ordering": ["-data", "-created_at"],
            },
        ),
    ]
