# Generated by Django 5.0 on 2025-12-29 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_despesatemplate_despesa"),
    ]

    operations = [
        migrations.CreateModel(
            name="Boletim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        db_index=True, max_length=20, unique=True, verbose_name="Número"
                    ),
                ),
                (
                    "socio",
                    models.CharField(
                        choices=[("BA", "Bruno"), ("RR", "Rafael")],
                        db_index=True,
                        max_length=2,
                        verbose_name="Sócio",
                    ),
                ),
                (
                    "mes",
                    models.IntegerField(
                        blank=True, db_index=True, null=True, verbose_name="Mês"
                    ),
                ),
                (
                    "ano",
                    models.IntegerField(
                        blank=True, db_index=True, null=True, verbose_name="Ano"
                    ),
                ),
                (
                    "data_emissao",
                    models.DateField(db_index=True, verbose_name="Data Emissão"),
                ),
                (
                    "data_pagamento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Pagamento"
                    ),
                ),
                (
                    "val_dia_nacional",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Valor Dia Nacional",
                    ),
                ),
                (
                    "val_dia_estrangeiro",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Valor Dia Estrangeiro",
                    ),
                ),
                (
                    "val_km",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Valor KM",
                    ),
                ),
                (
                    "total_ajudas_nacionais",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Total Ajudas Nacionais",
                    ),
                ),
                (
                    "total_ajudas_estrangeiro",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Total Ajudas Estrangeiro",
                    ),
                ),
                (
                    "total_kms",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Total KMs",
                    ),
                ),
                (
                    "valor_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Valor Total",
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                        verbose_name="Valor (antigo)",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        blank=True, null=True, verbose_name="Descrição (antigo)"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[("PENDENTE", "Pendente"), ("PAGO", "Pago")],
                        db_index=True,
                        default="PENDENTE",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                ("nota", models.TextField(blank=True, null=True, verbose_name="Nota")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Boletim",
                "verbose_name_plural": "Boletins",
                "db_table": "boletins",
                "ordering": ["-data_emissao", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BoletimLinha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordem", models.IntegerField(verbose_name="Ordem")),
                ("servico", models.TextField(verbose_name="Serviço")),
                (
                    "localidade",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Localidade"
                    ),
                ),
                (
                    "data_inicio",
                    models.DateField(blank=True, null=True, verbose_name="Data Início"),
                ),
                (
                    "hora_inicio",
                    models.TimeField(blank=True, null=True, verbose_name="Hora Início"),
                ),
                (
                    "data_fim",
                    models.DateField(blank=True, null=True, verbose_name="Data Fim"),
                ),
                (
                    "hora_fim",
                    models.TimeField(blank=True, null=True, verbose_name="Hora Fim"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("NACIONAL", "Nacional"),
                            ("ESTRANGEIRO", "Estrangeiro"),
                        ],
                        default="NACIONAL",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "dias",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="Dias"
                    ),
                ),
                ("kms", models.IntegerField(default=0, verbose_name="KMs")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "boletim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linhas",
                        to="core.boletim",
                        verbose_name="Boletim",
                    ),
                ),
                (
                    "projeto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.projeto",
                        verbose_name="Projeto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Linha de Boletim",
                "verbose_name_plural": "Linhas de Boletim",
                "db_table": "boletim_linhas",
                "ordering": ["boletim", "ordem"],
            },
        ),
    ]
