# Generated by Django - Merge migration
# Merges the two parallel migration paths:
# - Fiscal sequence (ending in 0006_fiscal_fields)
# - Socio/Tags sequence (ending in 0008_force_fix_boletim_socio)

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_fiscal_fields'),
        ('core', '0008_force_fix_boletim_socio'),
    ]

    operations = [
        # Empty migration - just merges the two paths
    ]
