# Generated by Django 5.0 on 2026-01-23
"""
Migration para substituir campo 'estado' por 'cancelado' no modelo Projeto

Esta migration realiza 3 operações sequenciais:
1. Adiciona o campo 'cancelado' (BooleanField, default=False)
2. Migra dados: projetos com estado='ANULADO' → cancelado=True
3. Remove o campo 'estado' (CharField)
"""
from django.db import migrations, models


def migrate_estado_to_cancelado(apps, schema_editor):
    """
    Migração de dados: estado='ANULADO' → cancelado=True
    Todos os outros estados → cancelado=False (já é o default)
    """
    Projeto = apps.get_model('core', 'Projeto')
    db_alias = schema_editor.connection.alias

    # Marcar projetos ANULADO como cancelado=True
    Projeto.objects.using(db_alias).filter(estado='ANULADO').update(cancelado=True)

    # Todos os outros já estão com cancelado=False (default do campo)


def reverse_migrate_cancelado_to_estado(apps, schema_editor):
    """
    Reverse migration: cancelado=True → estado='ANULADO'
                      cancelado=False → estado='ATIVO' (default seguro)
    """
    Projeto = apps.get_model('core', 'Projeto')
    db_alias = schema_editor.connection.alias

    # Restaurar estado='ANULADO' para projetos cancelados
    Projeto.objects.using(db_alias).filter(cancelado=True).update(estado='ANULADO')

    # Restaurar estado='ATIVO' para projetos não cancelados
    Projeto.objects.using(db_alias).filter(cancelado=False).update(estado='ATIVO')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_fiscal_tags_system'),
    ]

    operations = [
        # Operação 1: Adicionar campo 'cancelado'
        migrations.AddField(
            model_name='projeto',
            name='cancelado',
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text='Marcar como True se o projeto foi cancelado/anulado',
                verbose_name='Cancelado'
            ),
        ),

        # Operação 2: Migrar dados (estado → cancelado)
        migrations.RunPython(
            migrate_estado_to_cancelado,
            reverse_code=reverse_migrate_cancelado_to_estado
        ),

        # Operação 3: Remover campo 'estado'
        migrations.RemoveField(
            model_name='projeto',
            name='estado',
        ),
    ]
