# Generated by Django 5.0 on 2026-01-23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_projeto_remove_estado_add_cancelado'),
    ]

    operations = [
        # Add cancelado column to core_historicalprojeto
        migrations.RunSQL(
            sql="""
                ALTER TABLE core_historicalprojeto
                ADD COLUMN IF NOT EXISTS cancelado BOOLEAN NOT NULL DEFAULT FALSE;

                CREATE INDEX IF NOT EXISTS core_historicalprojeto_cancelado_idx
                ON core_historicalprojeto(cancelado);
            """,
            reverse_sql="""
                DROP INDEX IF EXISTS core_historicalprojeto_cancelado_idx;
                ALTER TABLE core_historicalprojeto DROP COLUMN IF EXISTS cancelado;
            """
        ),
        # Remove estado column from core_historicalprojeto
        migrations.RunSQL(
            sql="""
                ALTER TABLE core_historicalprojeto DROP COLUMN IF EXISTS estado;
            """,
            reverse_sql="""
                ALTER TABLE core_historicalprojeto
                ADD COLUMN estado VARCHAR(20) DEFAULT 'ATIVO';
            """
        ),
    ]
